# Generated by Django 4.2.6 on 2023-10-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='picture_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
