# Generated by Django 4.2.6 on 2023-10-29 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles_app', '0003_remove_articles_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='articles',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='articles',
            name='picture_1024_768',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='articles',
            name='picture_1366_768',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='articles',
            name='picture_1600_1200',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='articles',
            name='picture_480_320',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='articles',
            name='picture_800_480',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.CreateModel(
            name='FavoritedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='articles_app.articles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
