# Generated by Django 4.2.6 on 2023-10-29 09:17

import articles_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_app', '0004_remove_articles_picture_url_articles_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=articles_app.models.image_path),
        ),
        migrations.AlterField(
            model_name='articles',
            name='picture_1024_768',
            field=models.ImageField(blank=True, null=True, upload_to=articles_app.models.image_path),
        ),
        migrations.AlterField(
            model_name='articles',
            name='picture_1366_768',
            field=models.ImageField(blank=True, null=True, upload_to=articles_app.models.image_path),
        ),
        migrations.AlterField(
            model_name='articles',
            name='picture_1600_1200',
            field=models.ImageField(blank=True, null=True, upload_to=articles_app.models.image_path),
        ),
        migrations.AlterField(
            model_name='articles',
            name='picture_480_320',
            field=models.ImageField(blank=True, null=True, upload_to=articles_app.models.image_path),
        ),
        migrations.AlterField(
            model_name='articles',
            name='picture_800_480',
            field=models.ImageField(blank=True, null=True, upload_to=articles_app.models.image_path),
        ),
    ]
